---

# this playbook deploys the chezbob site
- hosts: soda-dev-machines
  roles:
      - dev
      - redis
      - barcodei-server
      - barcode-server
      - mdb-server
      - vdb-server
      - soda-server
